app_blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'app_blog'
urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_tag_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    # path('<int:pk>/share/', views.post_share, name='post_share'),
    path('<int:pk>/share/', views.post_share, name='post_share'),
    path('<int:pk>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from app_blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('app_blog.urls', namespace='app_blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

app_blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

# Create your models here.
class Post(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Roboczy'
        PUBLISHED = 'PB', 'Opublikowany'
      
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    tags = TaggableManager()
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    objects = models.Manager()
    published = PublishedManager()
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('app_blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
    
    def __str__(self):
        return f"Komentarz utworzony przez {self.name} dla posta {self.post}"

app_blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=True, widget=forms.Textarea)
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        
        
class SearchForm(forms.Form):
    query = forms.CharField()

app_blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     template_name = 'blog/post/list.html'
#     paginate_by = 3
    
# Create your views here.
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    # try:
    #     post = Post.objects.get(id=pk)
    # except Post.DoesNotExist:
    #     raise Http404("Nie znaleziono posta.")
    
    # post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, publish__year=year, publish__month=month, publish__day=day, slug=post)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id).annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})


def post_share(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} zalecia Ci przeczytanie {post.title}"
            message = f"Przeczytaj {post.title} pod adresem {post_url}\n\n komentarze {cd['name']}: {cd['comments']}"
            send_mail(subject, message, cd['email'], [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A', config='polish') + SearchVector('body', weight='B', config='polish')
            search_query = SearchQuery(query, config='polish')
            # results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.3).order_by('-rank')
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gte=0.1).order_by('-similarity')
            
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

app_blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet" />
  </head>
  <body>
    <div id="content">
      {% block content %}

      {% endblock %}
    </div>

    <div id="sidebar">
      <h2>Mój blog</h2>
      <p>To jest mój blog. Dotychczas opublikowałem {% all_posts %} postów.</p>
      <p>
        <a href="{% url 'app_blog:post_feed' %}">Subskrybuj mój kanał RSS</a>
      </p>
      <h3>Najnowsze posty:</h3>
        {% show_latest_posts 3 %}
      <h3>Najczęściej komentowane posty</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
          {% for post in most_commented_posts %}
            <li>
              <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
          {% endfor %}
        </ul>
    </div>
  </body>
</html>

app_blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}
  Dodaj komentarz
{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Twój komentarz został dodany.</h2>
    <p>
      <a href="{{ post.get_absolute_url }}">Powrót do posta</a>
    </p>
  {% else %}
    {% include 'blog/post/includes/comment_form.html' %}
  {% endif %}
{% endblock %}

app_blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">Opublikowany {{ post.publish }} przez {{ post.author }}</p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url 'app_blog:post_share' post.id %}">Udostępnij post</a>
  </p>

  <h2>Podobne posty</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}Nie ma jeszcze podobnych postów.
  {% endfor %}
  {% with comments.count as total_comments %}
    <h2>{{ total_comments }} komentarzy</h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
        {{ comment.created }}</p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>Nie ma jeszcze żadnych komentarzy.</p>
  {% endfor %}
  {% include 'blog/post/includes/comment_form.html' %}
{% endblock %}

app_blog/templates/blog/post/includes/comment_form.html
<h2>Dodaj nowy komentarz</h2>
<form action="{% url 'app_blog:post_comment' post.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Dodaj komentarz" />
</form>

app_blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

app_blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
  Mój blog
{% endblock %}

{% block content %}
  <h1>Mój blog</h1>
  {% if tag %}
    <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    {% comment %} <h2><a href="{% url 'app_blog:post_detail' post.id %}">{{ post.title }}</a></h2> {% endcomment %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {% comment %} <p class="tags">Tagi: {{ post.tags.all|join:', ' }}</p> {% endcomment %}
    {% for tag in post.tags.all %}
      <a href="{% url 'app_blog:post_tag_list' tag.slug %}">
        {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
    {% endfor %}
    <p class="date">Opublikowany {{ post.publish }} przez {{ post.author }}</p>
    {{ post.body|markdown|truncatewords_html:10 }}
  {% endfor %}
    {% include "pagination.html" with page=posts %}
    {% comment %} {% include "pagination.html" with page=page_obj %} {% endcomment %}
{% endblock %}

app_blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %} Szukaj {% endblock %}

{% block content %}
    {% if query %}
        <h1>Posty zawierające "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Znaleziono {{ total_results }} wyników
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>Brak wyników dla podanego zapytania.</p>
        {% endfor %}
        <p><a href="{% url 'app_blog:post_search' %}">Szukaj ponownie</a></p>
    {% else %}
        <h1>Szukaj postów</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Szukaj">
        </form>
    {% endif %}
{% endblock %}

app_blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block content %}
  {% if sent %}
    <h2>Wiadomość e-mail została pomyślnie wysłana</h2>
    <p>"Wysłanie posta {{ post.title }}" do {{ form.cleaned_data.to }} zakończyło się sukcesem.</p>
  {% else %}
    <h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Wyślij wiadomośc e-mail" />
    </form>
  {% endif %}
{% endblock %}

app_blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
    {% endif %}

    <span class="current">Strona {{ page.number }} z {{ page.paginator.num_pages }}.</span>

    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Następna</a>
    {% endif %}
  </span>
</div>